# **String & Text Cleaning**

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [13]:
# Create DataFrame with strip spaces, uppercase, lowercase, and title case
df = pd.DataFrame(
    {
        "Category": ["   Electronics ", "furniture ", "  Clothing  ", "TOYS", "Geology-Books"]
    }
)
df

          Category
0     Electronics
1       furniture
2       Clothing
3             TOYS
4    Geology-Books

In [11]:
# Strip Spaces and convert to lowercase
df["Category_Cleaned"] = df["Category"].str.strip().str.lower()
df

          Category Category_Cleaned
0     Electronics       electronics
1       furniture         furniture
2       Clothing           clothing
3             TOYS             toys
4    Geology-Books    geology-books

In [12]:
# Replace Hyphen with Space
df["Category_Cleaned"] = df["Category_Cleaned"].str.replace("-", " ")
df

          Category Category_Cleaned
0     Electronics       electronics
1       furniture         furniture
2       Clothing           clothing
3             TOYS             toys
4    Geology-Books    geology books