# **Descriptive Statistics and Data Distributions**

- **Descriptive statistics:** summarize the data
- **Distribution analysis:** tells us how the values are spread.
### **Key Functions for Descriptive Statistics**
1. `df.describe()` Overall descriptive statistics
2. `df["col"].value_counts` Frequency of categorical values
3. `df.quantile(q)` Percentiles
4. `df.skew()` Distribution asymmetry
5. `df.kurt` Tail/extreme-value behavior

## Data Analysis Framework

```text
DATA
 │
 ├── CENTRAL TENDENCY
 │    ├── Mean
 │    ├── Median
 │    └── Mode
 │
 ├── DISPERSION
 │    ├── Standard Deviation
 │    ├── Variance
 │    └── IQR
 │
 └── DISTRIBUTION
      ├── Skewness
      ├── Kurtosis
      └── Shape
           │
           ↓
      VISUALIZATION
           ├── Histogram
           └── Boxplot

--------------

In [9]:
# Import libraries
import pandas as pd
import numpy as np

# Load Dataset - ecommerce sales
df = pd.read_csv("../datasets/ecommerce_sales.csv", parse_dates = ["order_date"])

In [10]:
# Display First Five Rows
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

### 1. Total Observations

In [11]:
# Total rows and cols
df.shape

(5000, 12)

## 2. Descriptive Statistics

In [14]:
# Core descriptive analysis
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [15]:
# For unit price and revenue
df[["unit_price", "revenue"]].describe()

        unit_price      revenue
count  5000.000000  5000.000000
mean    308.418774  1021.955148
std     169.259369   825.584219
min      15.150000    11.210000
25%     161.895000   354.527500
50%     309.890000   796.650000
75%     455.557500  1515.690000
max     599.960000  4119.330000

## 3. Measures of Dispersion

### 3.1 Range

In [17]:
# Measure range
df["revenue"].max() - df["revenue"].min()

np.float64(4108.12)

### 3.2 Variance
- Variance measures the average squared deviation from the mean.

In [18]:
# Calculate variance
df["revenue"].var()

np.float64(681589.3029775337)

### 3.3 Standard Deviation

In [19]:
# Calculate STD
df["revenue"].std()

np.float64(825.5842191911942)

### 3.4 Interquartile Range (IQR)
- IQR describes the spread of the middle 50% of the data.
- This is particularly useful for outlier detection.

In [22]:
# Using IQR to understand spread
Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)

IQR = Q3 - Q1
print("Q1 =", Q1, "Q3 = ", Q3, "IQR = ", IQR)

Q1 = 354.5275 Q3 =  1515.69 IQR =  1161.1625000000001

## 4. Data Distribution
- Distribution analysis tells us:
    - How are those values distributed?

### 4.1 skew() — Measure Asymmetry
- Skewness ≈ 0 → roughly symmetric
- Skewness > 0 → right-skewed
- Skewness < 0 → left-skewed

In [23]:
# Measure skewness
df["revenue"].skew()

np.float64(1.0017064603000962)

### 4.2 Identifying Skewness - Comparing Mean and Median
- Mean ≈ Median: distribution may be reasonably symmetric
- Mean > Median: indicate right skewness
- Mean < Median: indicate left skewness

In [28]:
# Compare mean and median
print("Mean = ", df["revenue"].mean())
print("Median = ", df["revenue"].median())

Mean =  1021.955148
Median =  796.65

### 4.3 kurt() — Measure Tail/Extreme-Value Behavior
- Kurtosis helps describe the tendency toward heavy or light tails/extreme observations relative to a normal distribution.

In [29]:
# Measure kurtosis
df["revenue"].kurt()

np.float64(0.345240422414856)

## 5. Categorical Distribution
### 5.1 value_counts()

In [31]:
# Distribution of products
df["product_category"].value_counts()

product_category
Electronics    1777
Clothing       1531
Home            969
Beauty          723
Name: count, dtype: int64

### 5.2 Categorical-level Descriptive Stats

In [37]:
# Calculate descriptive stats based on products
df.groupby("product_category", as_index = False)["revenue"].describe()

,product_category,count,mean,std,min,25%,50%,75%,max
0,Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
1,Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
2,Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
3,Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [44]:
# Percentage of products occur
df["product_category"].value_counts(normalize=True)*100

product_category
Electronics    35.54
Clothing       30.62
Home           19.38
Beauty         14.46
Name: proportion, dtype: float64

## 6. Missing Values

In [45]:
# calulate missing values in dataset
df.isna().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64