# **DateTime and Time Series Data**

In [14]:
# Import libraries 
import pandas as pd
import numpy as np

# Load dataset (ecommerce sales)
df = pd.read_csv("../datasets/ecommerce_sales.csv")

# display dataset
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [15]:
# Data types
df.dtypes

order_id              int64
order_date              str
customer_id           int64
product_category        str
region                  str
quantity              int64
unit_price          float64
discount            float64
payment_method          str
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

# 2. Convert order_date to datetime

In [16]:
# Convert order_date col to datetime format
df["order_date"] = pd.to_datetime(df['order_date'], errors = 'coerce') # errors="coerce" converts invalid dates into: NaT

In [17]:
# Verify datatypes
df.dtypes

order_id                     int64
order_date          datetime64[us]
customer_id                  int64
product_category               str
region                         str
quantity                     int64
unit_price                 float64
discount                   float64
payment_method                 str
delivery_days                int64
customer_rating            float64
revenue                    float64
dtype: object

In [18]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

# 3. Creating DateTime Index

In [19]:
# Setting index as date and time
df = df.set_index("order_date")

In [20]:
# Verify 
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[us]', name='order_date', length=5000, freq=None)

# 4. Feature Extraction
## 4.1 Calender Features

In [21]:
# Extract year
df["order_year"] = df.index.year
# Extract month
df["order_month"] = df.index.month
# Extract day
df["order_day"] = df.index.day
# Extract quarter
df["order_quarter"] = df.index.quarter

## 4.2 Week-related Features

In [22]:
# Extract Week
df["order_week"] = df.index.isocalendar().week.astype(int)
# Extract day of week
df["order_dayofweek"] = df.index.dayofweek

## 4.3 Extract Month and Day Names (labels)

In [23]:
# Extract month name
df["order_month_name"] = df.index.month_name()
# Extract day name
df["order_day_name"] = df.index.day_name()

## 4.4 Extract Weekend and Week-days

In [24]:
# Weekend indicator
df["day_type"] = np.where(df.index.dayofweek >= 5, "Weekend", "Working Day")

# 5. Revenue Analysis
## 5.1 Monthly Revenue

In [ ]:
# monthly revenue
monthly_revenue = df.resample("ME")["revenue"].sum()
monthly_revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

## 5.2 Daily Revenue

In [ ]:
# Daily revenue (same as provided in data)
daily_revenue = df.resample("D")["revenue"].sum()
daily_revenue

order_date
2022-01-01    1883.20
2022-01-02     304.10
2022-01-03     644.35
2022-01-04    2569.90
2022-01-05     468.56
               ...
2035-09-05     542.74
2035-09-06    1428.47
2035-09-07     176.06
2035-09-08     437.38
2035-09-09    1069.90
Freq: D, Name: revenue, Length: 5000, dtype: float64

## 5.3 Weekly Revenue

In [31]:
# Weekly revenue
weekly_revenue = df.resample("W")["revenue"].sum()
weekly_revenue

order_date
2022-01-02     2187.30
2022-01-09     9085.34
2022-01-16     9850.73
2022-01-23     5816.79
2022-01-30     8006.39
                ...
2035-08-12     6305.45
2035-08-19    11250.72
2035-08-26     6329.39
2035-09-02     3697.92
2035-09-09     3888.76
Freq: W-SUN, Name: revenue, Length: 715, dtype: float64

## 5.4 Quaterly Revenue

In [35]:
# Quaterly revenue
quaterly_revenue = df.resample("QE")["revenue"].sum()
quaterly_revenue.head()

order_date
2022-03-31     95843.06
2022-06-30    102258.53
2022-09-30     86663.76
2022-12-31     87058.95
2023-03-31     95118.92
Freq: QE-DEC, Name: revenue, dtype: float64

## 5.5 Annual Revenue

In [40]:
# Yearly revenue
annual_revenue = df.resample("YE")["revenue"].sum()
annual_revenue

order_date
2022-12-31    371824.30
2023-12-31    365915.79
2024-12-31    363209.13
2025-12-31    349802.33
2026-12-31    386369.69
2027-12-31    386151.91
2028-12-31    376844.80
2029-12-31    359239.24
2030-12-31    387884.46
2031-12-31    365250.83
2032-12-31    386584.63
2033-12-31    408725.72
2034-12-31    363239.55
2035-12-31    238733.36
Freq: YE-DEC, Name: revenue, dtype: float64

In [32]:
df.head(15)

,order_id,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,order_year,order_month,order_day,order_quarter,order_week,order_dayofweek,order_month_name,order_day_name,day_type
order_date,,,,,,,,,,,,,,,,,,,,
2022-01-01,10001,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022,1,1,1,52,5,January,Saturday,Weekend
2022-01-02,10002,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022,1,2,1,52,6,January,Sunday,Weekend
2022-01-03,10003,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,2022,1,3,1,1,0,January,Monday,Working Day
2022-01-04,10004,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022,1,4,1,1,1,January,Tuesday,Working Day
2022-01-05,10005,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022,1,5,1,1,2,January,Wednesday,Working Day
2022-01-06,10006,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10,2022,1,6,1,1,3,January,Thursday,Working Day
2022-01-07,10007,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45,2022,1,7,1,1,4,January,Friday,Working Day
2022-01-08,10008,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01,2022,1,8,1,1,5,January,Saturday,Weekend
2022-01-09,10009,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97,2022,1,9,1,1,6,January,Sunday,Weekend
2022-01-10,10010,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39,2022,1,10,1,2,0,January,Monday,Working Day
2022-01-11,10011,1466,Clothing,West,6,318.88,0.02,COD,7,1.4,1875.01,2022,1,11,1,2,1,January,Tuesday,Working Day
2022-01-12,10012,1214,Electronics,West,3,384.71,0.14,COD,11,1.9,992.55,2022,1,12,1,2,2,January,Wednesday,Working Day
2022-01-13,10013,1330,Beauty,South,7,483.41,0.30,COD,6,1.4,2368.71,2022,1,13,1,2,3,January,Thursday,Working Day
2022-01-14,10014,1458,Clothing,West,7,279.48,0.26,COD,8,1.4,1447.71,2022,1,14,1,2,4,January,Friday,Working Day
2022-01-15,10015,1087,Clothing,East,4,493.23,0.18,Card,9,3.1,1617.79,2022,1,15,1,2,5,January,Saturday,Weekend