# **DateTime and Time Series Data**

In [127]:
# Import libraries 
import pandas as pd
import numpy as np

# Load dataset (ecommerce sales)
df = pd.read_csv("../datasets/ecommerce_sales.csv")

# display dataset
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [128]:
# Data types
df.dtypes

order_id              int64
order_date              str
customer_id           int64
product_category        str
region                  str
quantity              int64
unit_price          float64
discount            float64
payment_method          str
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

# 2. Convert order_date to datetime

In [129]:
# Convert order_date col to datetime format
df["order_date"] = pd.to_datetime(df['order_date'], errors = 'coerce') # errors="coerce" converts invalid dates into: NaT

In [130]:
# Verify datatypes
df.dtypes

order_id                     int64
order_date          datetime64[us]
customer_id                  int64
product_category               str
region                         str
quantity                     int64
unit_price                 float64
discount                   float64
payment_method                 str
delivery_days                int64
customer_rating            float64
revenue                    float64
dtype: object

In [131]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

# 3. Creating DateTime Index

In [132]:
# Setting index as date and time
df = df.set_index("order_date")

In [133]:
# Verify 
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[us]', name='order_date', length=5000, freq=None)

# 4. Feature Extraction
## 4.1 Calender Features

In [134]:
# Extract year
df["order_year"] = df.index.year
# Extract month
df["order_month"] = df.index.month
# Extract day
df["order_day"] = df.index.day
# Extract quarter
df["order_quarter"] = df.index.quarter

## 4.2 Week-related Features

In [135]:
# Extract Week
df["order_week"] = df.index.isocalendar().week.astype(int)
# Extract day of week
df["order_dayofweek"] = df.index.dayofweek

## 4.3 Extract Month and Day Names (labels)

In [136]:
# Extract month name
df["order_month_name"] = df.index.month_name()
# Extract day name
df["order_day_name"] = df.index.day_name()

## 4.4 Extract Weekend and Week-days

In [137]:
# Weekend indicator
df["day_type"] = np.where(df.index.dayofweek >= 5, "Weekend", "Working Day")

# 5. Revenue Analysis
## 5.1 Monthly Revenue

In [141]:
monthly_revenue = df.resample("ME")["revenue"].sum()
monthly_revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [138]:
df

,order_id,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,order_year,order_month,order_day,order_quarter,order_week,order_dayofweek,order_month_name,order_day_name,day_type
order_date,,,,,,,,,,,,,,,,,,,,
2022-01-01,10001,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022,1,1,1,52,5,January,Saturday,Weekend
2022-01-02,10002,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022,1,2,1,52,6,January,Sunday,Weekend
2022-01-03,10003,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,2022,1,3,1,1,0,January,Monday,Working Day
2022-01-04,10004,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022,1,4,1,1,1,January,Tuesday,Working Day
2022-01-05,10005,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022,1,5,1,1,2,January,Wednesday,Working Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035-09-05,14996,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74,2035,9,5,3,36,2,September,Wednesday,Working Day
2035-09-06,14997,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47,2035,9,6,3,36,3,September,Thursday,Working Day
2035-09-07,14998,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06,2035,9,7,3,36,4,September,Friday,Working Day
2035-09-08,14999,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38,2035,9,8,3,36,5,September,Saturday,Weekend
2035-09-09,15000,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90,2035,9,9,3,36,6,September,Sunday,Weekend