# **Outliers Detection using Statistical Rules**

### **Outliers:** 
- Data points that fall outside the normal range, representing extreme values.
- These values can distort the mean and median of dataset.
### **Methods:**
 1. IQR Method
     - Use: Skewed / non-normal data
 2. Z-score Method: 
    - How many standard deviations away from the mean is an observation? Threshold: |z| > 3
    - Use: Approximately normally distributed data
 3. Domain-driven Thresholds/Expert

---------------

# 1. Import Libraries and Load Dataset

In [33]:
# Import libraries
import pandas as pd 
import numpy as np

# Load Dataset
df = pd.read_csv("../datasets/ecommerce_sales.csv", parse_dates = ["order_date"])
# display first five rows
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

# 2. IQR Method

In [34]:
# Implement IQR in Pandas
Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [35]:
# Identify potential outliers
outliers_iqr = df[
    (df["revenue"] < lower_bound) |
    (df["revenue"] > upper_bound)
    ]
# Verification
outliers_iqr.shape

(67, 12)

In [36]:
# Inspect
outliers_iqr[["revenue", "product_category", "quantity"]].head()

     revenue product_category  quantity
39   3640.56             Home         7
69   3338.37           Beauty         7
102  3449.50         Clothing         6
126  3472.39         Clothing         7
157  3917.54      Electronics         7

In [37]:
# Remove from data
df_clean = df[
    (df["revenue"] >= lower_bound) &
    (df["revenue"] <= upper_bound)
]
# Verify
df_clean.shape

(4933, 12)

# 3. Z-score Method

In [38]:
# import library
from scipy.stats import zscore

In [39]:
# Apply z-score method
df["revenue_zscore"] = zscore(df["revenue"])
outliers_zscore = df[df["revenue_zscore"].abs() > 3] 

# verification
outliers_zscore.shape

(26, 13)

In [40]:
# Remove outliers from data
df_zclean = df[df["revenue_zscore"].abs() <= 3]

In [41]:
# verify rows
df_zclean.shape

(4974, 13)